steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/uber-react:latest', '.']
  timeout: 500s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/uber-react:latest']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'sa-frontend-deployment.yaml', '--force']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gkecluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'sa-frontend-lb.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gkecluster'