steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/csye7220-311404/uber-react:$COMMIT_SHA', '.']
#   timeout: 500s

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/csye7220-311404/uber-react:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'sa-frontend-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gkecluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'sa-frontend-lb.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gkecluster'

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=sa-frontend-deployment.yaml
#   - --image=gcr.io/csye7220-311404/uber-react:eafaef900960c0468a6fe36939ddd556bc917542
#   - --location=us-east1
#   - --cluster=gkecluster